# Generated by Django 2.0 on 2017-12-30 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0002_auto_20171214_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ancestry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancestry_country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=200)),
                ('f_ancestry_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='expo.Ancestry')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('museum_title', models.CharField(max_length=200)),
                ('museum_country', models.CharField(max_length=100)),
                ('museum_city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='painting',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='painting',
            name='text',
        ),
        migrations.AddField(
            model_name='painting',
            name='art_image',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='f_artist_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='expo.Artist'),
        ),
        migrations.AddField(
            model_name='painting',
            name='f_genre_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='expo.Genre'),
        ),
        migrations.AddField(
            model_name='painting',
            name='f_museum_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='expo.Museum'),
        ),
        migrations.AddField(
            model_name='painting',
            name='f_period_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='expo.Period'),
        ),
    ]
