# Generated by Django 2.0 on 2017-12-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0003_auto_20171230_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancestry',
            name='ancestry_country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='museum',
            name='museum_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='museum_country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='museum',
            name='museum_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='painting',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='period',
            name='period_title',
            field=models.CharField(max_length=50),
        ),
    ]
