# Generated by Django 2.0 on 2017-12-31 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0005_auto_20171231_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='museum',
            name='museum_city',
        ),
        migrations.RemoveField(
            model_name='museum',
            name='museum_country',
        ),
        migrations.AddField(
            model_name='city',
            name='f_country',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='expo.Country'),
        ),
        migrations.AddField(
            model_name='museum',
            name='f_country',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='expo.Country'),
        ),
    ]
