# Generated by Django 2.0 on 2018-01-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0008_imagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
