# Generated by Django 2.0 on 2018-01-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0009_delete_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='art_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
