# Generated by Django 2.0 on 2018-01-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0010_auto_20180104_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='counter_popular',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
