# Generated by Django 2.0 on 2018-01-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0011_painting_counter_popular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='counter_popular',
            new_name='counter_popularity',
        ),
    ]
