# Generated by Django 2.0 on 2018-01-22 18:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0012_auto_20180113_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamousPaintings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', multiselectfield.db.fields.MultiSelectField(choices=[('Mona Lisa', 'Mona Lisa'), ('Starry Night', 'Starry Night'), ('The Last Supper', 'The Last Supper'), ('The Creation of Adam', 'The Creation of Adam'), ('Guernica', 'Guernica'), ('Django', 'Django')], max_length=75)),
            ],
        ),
    ]
