# Generated by Django 2.0 on 2018-01-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0013_famouspaintings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mona Lisa', 'Mona Lisa'), ('Starry Night', 'Starry Night'), ('The Last Supper', 'The Last Supper'), ('The Creation of Adam', 'The Creation of Adam'), ('Guernica', 'Guernica'), ('Django', 'Django')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='FamousPaintings',
        ),
    ]
