# Generated by Django 2.0 on 2018-01-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0015_auto_20180122_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='status',
            field=models.CharField(choices=[('on', 'Online'), ('off', 'Offline')], default='on', max_length=3),
        ),
    ]
